name: Upload Packages to GitHub Release
description: "Create or update a GitHub release and upload packages with fixed names"

inputs:
  artifact_name:
    description: 'Artifact name for download'
    required: false
    default: 'Packages'
  package_name:
    description: 'Base package name, defaults to repository name'
    required: false
    default: ''
  release_name:
    description: 'Target release name, defaults to current tag'
    required: false
    default: ''
  version:
    description: 'Version string to append to package name'
    required: false
    default: ''
  extensions:
    description: 'Space-separated list of package file extensions'
    required: false
    default: 'deb ddeb rpm'
  create_force:
    description: 'Force create the release if not exists, defaults false'
    required: false
    default: ''
  clobber:
    description: 'Overwrite existing assets if they exist. Defaults to false (skip if exists)'
    required: false
    default: ''
  fallback_to_artifacts:
    description: 'Try to download artifacts from successful CI workflow if cache missed'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Check available caches COMPOSITE ACTION
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        matrix_combinations=(
          "pxf-packages-6-devel"
          "pxf-packages-6-stable"
          "pxf-packages-7-devel"
          "pxf-packages-7-stable"
          "deb-packages"
          "pxf-packages"
          "Packages"
        )
        
        for prefix in "${matrix_combinations[@]}"; do
          key="${prefix}-${{ github.sha }}"
          cache_info=$(gh cache list --key "$key" 2>/dev/null || true)
          if [ -n "$cache_info" ] && [ "$cache_info" != "[]" ]; then
            echo "Cache found: $key"
          else
            echo "Cache not found: $key"
          fi
        done

    - name: Restore Debian artifacts from cache
      uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ inputs.artifact_name }}
        key:  ${{ inputs.artifact_name }}-${{ github.sha }}

    - name: Get CI workflow run info
      if: steps.cache-restore.outputs.cache-hit != 'true'
      id: get-run-info
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        result=$(gh run list --workflow "Greengage CI" --limit 100 \
          --json conclusion,headSha,event,headBranch,databaseId,url \
          --jq 'map(select(.headSha == "'"${{ github.sha }}"'" and .event == "push" and .headBranch == "'"${{ github.event.release.tag_name }}"'")) |
          .[0]')
        
        conclusion=$(echo "$result" | jq -r '.conclusion')
        run_id=$(echo "$result" | jq -r '.databaseId')
        run_url=$(echo "$result" | jq -r '.url')
        
        echo "conclusion=$conclusion" >> $GITHUB_OUTPUT
        echo "run_id=$run_id" >> $GITHUB_OUTPUT
        echo "run_url=$run_url" >> $GITHUB_OUTPUT

    - name: Try to restore packages from GitHub artifacts
      if: steps.cache-restore.outputs.cache-hit != 'true' && inputs.fallback_to_artifacts == 'true' && steps.get-run-info.outputs.conclusion == 'success'
      id: try-restore
      uses: actions/download-artifact@v4
      with:
        run-id: ${{ steps.get-run-info.outputs.run_id }}
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.artifact_name }}

    - name: Check build status if cache missed
      if: steps.cache-restore.outputs.cache-hit != 'true' && (inputs.fallback_to_artifacts != 'true' || steps.get-run-info.outputs.conclusion != 'success')
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        conclusion="${{ steps.get-run-info.outputs.conclusion }}"
        run_id="${{ steps.get-run-info.outputs.run_id }}"
        run_url="${{ steps.get-run-info.outputs.run_url }}"
        
        if [ -z "$conclusion" ] || [ "$conclusion" = "success" ]; then
          echo "ERROR: Cache miss. No artifacts found for tag: ${{ github.event.release.tag_name }}"
          if [ -n "$run_id" ] && [ "$run_id" != "null" ]; then
            echo "Previous run: https://github.com/${{ github.repository }}/actions/runs/$run_id"
            echo "Click 'Re-run all jobs' to rebuild cache"
          else
            echo "No CI workflow triggered for this tag"
            echo "Possible reasons:"
            echo "  - Tag does not match workflow filter pattern (check 'tags:' in CI workflow)"
            echo "  - GitHub Actions permissions prevent workflow execution"
            echo "  - CI workflow configuration error"
            echo "  - Other unexpected failures in workflow triggering"
            echo -e "\nEnsure 'Greengage CI' workflow runs successfully on tag: ${{ github.event.release.tag_name }}"
            echo "Check workflow configuration and permissions."
          fi
          echo -e "\nAfter successful build, restart this release workflow."
        else
          echo "ERROR: Previous build failed: $conclusion"
          if [ -n "$run_id" ] && [ "$run_id" != "null" ]; then
            echo "Failed run: https://github.com/${{ github.repository }}/actions/runs/$run_id"
            echo "Click 'Re-run all jobs' after fixing issues"
          fi
        fi
        exit 1

    - name: List downloaded files
      shell: bash
      run: find "${{ inputs.artifact_name }}" -type f

    - name: Create release if not exists
      if: inputs.create_force != ''
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_NAME: ${{ inputs.release_name }}
        PACKAGE_NAME: ${{ inputs.package_name }}
      run: |
        PACKAGE_NAME=${PACKAGE_NAME:-${GITHUB_REPOSITORY#*/}}
        RELEASE_NAME=${RELEASE_NAME:-${GITHUB_REF#refs/tags/}}

        for var in PACKAGE_NAME RELEASE_NAME ; do
          if [ -z "${!var}" ] ; then
            echo "Can't determine $var"
            exit 1
          fi
        done

        if ! gh release view "$RELEASE_NAME" > /dev/null 2>&1; then
          gh release create "$RELEASE_NAME" \
            --title "Release $RELEASE_NAME" \
            --notes "$PACKAGE_NAME $RELEASE_NAME
        Built from commit: $GITHUB_SHA
        Workflow run: $GITHUB_RUN_NUMBER"
        else
          echo "Release $RELEASE_NAME already exists, skipping creation."
        fi

    - name: Check release exists
      shell: bash
      id: check_release
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_NAME: ${{ inputs.release_name }}
      run: |
        RELEASE_NAME="${RELEASE_NAME:-${GITHUB_REF#refs/tags/}}"
        if gh release view "$RELEASE_NAME" > /dev/null 2>&1; then
          echo "Release '$RELEASE_NAME' exists, proceeding with upload"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "Release '$RELEASE_NAME' not found, skipping upload"
        fi

    - name: Move and upload packages
      if: steps.check_release.outputs.exists == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_NAME: ${{ inputs.release_name }}
        PACKAGE_NAME: ${{ inputs.package_name }}
      run: |
        PACKAGE_NAME=${PACKAGE_NAME:-${GITHUB_REPOSITORY#*/}}
        RELEASE_NAME=${RELEASE_NAME:-${GITHUB_REF#refs/tags/}}

        for var in PACKAGE_NAME RELEASE_NAME ; do
          if [ -z "${!var}" ] ; then
            echo "Can't determine $var"
            exit 1
          fi
        done

        shopt -s nullglob
        
        for ext in ${{ inputs.extensions }}; do
          files=("${{ inputs.artifact_name }}"/*.$ext)
          if [ ${#files[@]} -ne 1 ]; then
            echo "Expected exactly one *.$ext file, found ${#files[@]}"
            exit 1
          fi

          target="${{ inputs.artifact_name }}/${PACKAGE_NAME}${{ inputs.version }}.$ext"
          mv -f "${files[0]}" "$target"
          echo "Uploading $target"
          gh release upload "$RELEASE_NAME" "$target" ${{ inputs.clobber == 'true' && '--clobber' || '' }}
        done
