name: Upload Packages to GitHub Release
description: "Create or update a GitHub release and upload packages with fixed names"

inputs:
  artifact_name:
    description: 'Artifact name for download'
    required: false
    default: 'Packages'
  package_name:
    description: 'Base package name, defaults to repository name'
    required: false
    default: ''
  release_name:
    description: 'Target release name, defaults to current tag'
    required: false
    default: ''
  version:
    description: 'Version string to append to package name'
    required: false
    default: ''
  extensions:
    description: 'Space-separated list of package file extensions'
    required: false
    default: 'deb ddeb rpm'
  create_force:
    description: 'Force create the release if not exists, defaults false'
    required: false
    default: ''
  clobber:
    description: 'Overwrite existing assets if they exist. Defaults to false (skip if exists)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Restore Debian artifacts from cache
      uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ inputs.artifact_name }}
        key:  ${{ inputs.artifact_name }}-${{ github.sha }}

    - name: Check build status if cache missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        conclusion=$(gh run list --workflow "Greengage CI" --limit 100 \
          --json conclusion,headSha,event,headBranch \
          --jq 'map(select(.headSha == "'"${{ github.sha }}"'" and .event == "push" and .headBranch == "'"${{ github.event.release.tag_name }}"'")) |
          .[0].conclusion')

        if [ -z "$conclusion" ] || [ "$conclusion" = "success" ]; then
          # echo "WARNING: Cache miss. Triggering new build..."
          # gh workflow run ".github/workflows/greengage-ci.yml" --ref "${{ github.event.release.tag_name }}"
          # gh workflow run ".github/workflows/greengage-release.yml" --ref "${{ github.event.release.tag_name }}"
          # echo "WARNING: Build and Release workflows queued. This workflow will fail. New release will run after build."
          echo "WARNING: The previous build for this tag succeeded, but the cache is missing."
          echo "      1. Rerun the build workflow with event 'push' on tag '${{ github.event.release.tag_name }}'"
          echo "      2. After the build completes, rerun this release workflow"
        else
          echo "ERROR: Previous TAG Build failed: $conclusion. Fix it manually."
        fi
        exit 1

    - name: List downloaded files
      shell: bash
      run: find "${{ inputs.artifact_name }}" -type f

    - name: Create release if not exists
      if: inputs.create_force != ''
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_NAME: ${{ inputs.release_name }}
        PACKAGE_NAME: ${{ inputs.package_name }}
      run: |
        PACKAGE_NAME=${PACKAGE_NAME:-${GITHUB_REPOSITORY#*/}}
        RELEASE_NAME=${RELEASE_NAME:-${GITHUB_REF#refs/tags/}}

        for var in PACKAGE_NAME RELEASE_NAME ; do
          if [ -z "${!var}" ] ; then
            echo "Can't determine $var"
            exit 1
          fi
        done

        if ! gh release view "$RELEASE_NAME" > /dev/null 2>&1; then
          gh release create "$RELEASE_NAME" \
            --title "Release $RELEASE_NAME" \
            --notes "$PACKAGE_NAME $RELEASE_NAME
        Built from commit: $GITHUB_SHA
        Workflow run: $GITHUB_RUN_NUMBER"
        else
          echo "Release $RELEASE_NAME already exists, skipping creation."
        fi

    - name: Check release exists
      shell: bash
      id: check_release
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_NAME: ${{ inputs.release_name }}
      run: |
        RELEASE_NAME="${RELEASE_NAME:-${GITHUB_REF#refs/tags/}}"
        if gh release view "$RELEASE_NAME" > /dev/null 2>&1; then
          echo "Release '$RELEASE_NAME' exists, proceeding with upload"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "Release '$RELEASE_NAME' not found, skipping upload"
        fi

    - name: Move and upload packages
      if: steps.check_release.outputs.exists == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        RELEASE_NAME: ${{ inputs.release_name }}
        PACKAGE_NAME: ${{ inputs.package_name }}
      run: |
        PACKAGE_NAME=${PACKAGE_NAME:-${GITHUB_REPOSITORY#*/}}
        RELEASE_NAME=${RELEASE_NAME:-${GITHUB_REF#refs/tags/}}

        for var in PACKAGE_NAME RELEASE_NAME ; do
          if [ -z "${!var}" ] ; then
            echo "Can't determine $var"
            exit 1
          fi
        done

        shopt -s nullglob
        
        for ext in ${{ inputs.extensions }}; do
          files=("${{ inputs.artifact_name }}"/*.$ext)
          if [ ${#files[@]} -ne 1 ]; then
            echo "Expected exactly one *.$ext file, found ${#files[@]}"
            exit 1
          fi

          target="${{ inputs.artifact_name }}/${PACKAGE_NAME}${{ inputs.version }}.$ext"
          mv -f "${files[0]}" "$target"
          echo "Uploading $target"
          gh release upload "$RELEASE_NAME" "$target" ${{ inputs.clobber == 'true' && '--clobber' || '' }}
        done
