name: Check clang-format

on:
  workflow_call:

jobs:
  check-clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: |
          set -e
          sudo apt install -y git parallel clang-format

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          submodules: recursive

      - name: Check clang-format
        run: |
          set -eu -o pipefail
          clang-format --version
          src/tools/fmt gen
          git diff --exit-code
          src/tools/fmt chk
