name: Greengage Reusable Cleanup Workflow

on:
  workflow_call:
    inputs:
      version:
        description: 'Version derived from tag (e.g., 6 or 7)'
        required: true
        type: string
      target_os:
        description: 'Target OS'
        required: true
        type: string
      target_os_version:
        description: 'Target OS version'
        required: false
        type: string
        default: ''
    secrets:
      ghcr_token:
        description: 'GitHub token for GHCR access'
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up crane
        uses: imjasonh/setup-crane@v0.3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr_token }}

      - name: Delete branch images
        env:
          REF: ${{ github.event.ref }}
        run: |
          branch_name=$(sed 's#refs/heads/##' <<< $REF)
          dev_tag=$(echo "$branch_name" | sed 's/[^a-zA-Z0-9._-]/_/g')
          if [ -z "$dev_tag" ]; then
            echo "Can't define Development's tag from Branch name '$branch_name'"
            exit 0
          fi
          IMAGE=ghcr.io/${{ github.repository }}/ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }}
          IMAGE=${IMAGE,,}
          digest=$(crane digest $IMAGE:$dev_tag || echo "")
          if [ -z "$digest" ]; then
            echo "No image found for tag $dev_tag"
            exit 0
          fi
          tags=$(crane ls $IMAGE)
          for tag in $tags; do
            if [ "$tag" != "latest" ]; then
              echo "Operate with tag '$tag'"
              tag_digest=$(crane digest $IMAGE:$tag || echo "")
              echo "Get tag digest '$tag_digest'"
              if [ "$tag_digest" == "$digest" ]; then
                echo "Attempting to delete '$IMAGE:$tag' with crane"
                if ! crane delete $IMAGE:$tag; then
                  echo "crane delete failed for '$IMAGE:$tag', attempting GitHub API"
                  package_name=$(echo "ggdb${{ inputs.version }}_${{ inputs.target_os }}${{ inputs.target_os_version }}" | tr '[:upper:]' '[:lower:]')
                  echo "Get package_name '$package_name'"
                  api_response=$(curl -s -H "Authorization: Bearer ${{ secrets.ghcr_token }}" \
                    -H "Accept: application/vnd.github+json" \
                    "https://api.github.com/repos/${{ github.repository }}/packages/container/$package_name/versions")
                  echo "Get api_response '$api_response'"
                  error_message=$(echo "$api_response" | jq -r '.message // empty')
                  if [ -n "$error_message" ]; then
                    echo "API error: $error_message"
                    continue
                  fi
                  version_id=$(echo "$api_response" | jq -r ".[] | select(.metadata.container.tags[]? == \"$tag\") | .id" || echo "")
                  if [ -n "$version_id" ]; then
                    echo "Deleting tag $tag (version ID: $version_id) via GitHub API"
                    curl -X DELETE \
                      -H "Authorization: Bearer ${{ secrets.ghcr_token }}" \
                      -H "Accept: application/vnd.github+json" \
                      "https://api.github.com/repos/${{ github.repository }}/packages/container/$package_name/versions/$version_id" || true
                  else
                    echo "No version ID found for tag $tag"
                  fi
                else
                  echo "Successfully deleted tag $tag with crane"
                fi
              fi
            fi
          done

